sudo: required

language: python


services:
  - docker

stages:
  - name: build_deploy_docs


before_install:
  - docker pull f5devcentral/containthedocs:latest


install:
  - travis_retry pip install awscli --upgrade



jobs:
  include:
    - stage: build
      skip_cleanup: true
      name: build_docs_site
      before_script:
        - aws s3 sync s3://ak-poc-clouddocs-ci/configs/travis-ci-playground ./temp_config/
        - mkdir ./script
        - cp ./temp_config/docker-docs.sh ./script/docker-docs.sh
        - cp ./temp_config/conf.py ./docs/conf.py
        - chmod -R 755 script
      script:
        - ls -la
        - ls -la ./script
        - make docker-html
      deploy:
        skip_cleanup: true
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: ak-poc-clouddocs-ci
        local_dir: docs/_build/html
        upload_dir: travis-ci-site
        on:
          branch: master
          repo: andreykashcheev/travis-ci-playground
      notifications:
        email:
          recipients:
            - a.kashcheev@f5.com
        webhooks: https://outlook.office.com/webhook/ef7d7702-cc7e-496c-9408-0768c9221005@dd3dfd2f-6a3b-40d1-9be0-bf8327d81c50/TravisCI/b1d06904d63547518ac6b6307af9e57d/b13eeba0-6263-4ea3-b582-48a8fd612f47