sudo: required

language: python


services:
  - docker

stages:
  - name: prepare
  - name: build
  - name: deploy


before_install:
  - docker pull f5devcentral/containthedocs:latest


install:
  - travis_retry pip install awscli --upgrade



jobs:
  include:
    - stage: prepare
      name: pull_configs
      skip_cleanup: true
      script:
        - aws s3 sync s3://ak-poc-clouddocs-ci/configs/ve-public-cloud ./temp_config/
        - mkdir ./scripts
        - chmod 755 scripts
        - cp ./temp_config/docker-docs.sh ./scripts/docker-docs.sh
        - cp ./temp_config/conf.py ./docs/conf.py
    - stage: build
      skip_cleanup: true
      name: build_docs_site
      script:
        - ./scripts/docker-docs.sh
    - stage: deploy
      name: deploy_to_s3
      provider: s3
      access_key_id: $AWS_ACCESS_KEY_ID
      secret_access_key: $AWS_SECRET_ACCESS_KEY
      bucket: ak-poc-clouddocs-ci
      local_dir: docs/_build/html
      upload_dir: travis-ci-site
      on:
        branch: master
        repo: andreykashcheev/travis-ci-playground
